### ISSUE TITLE
Getting AssertionError while running RABBIT on list of users

### ISSUE THREAD

**Issue by uhourri** [natarajan-chidambaram/RABBIT#50]
**Describe the bug**
I ran RABBIT on a list of 25 users, that I provided in a text input file, as mentioned below :

$ rabbit --input-file logins.txt --csv output.csv --key GITHUB_KEY --verbose

I got this following error:

 60%|████████████████████████████████████████████████████████████▌                                        | 15/25 [00:15<00:10,  1.01s/it]
Traceback (most recent call last):
  File "/home/youness/gh-events-bigquery/.rabbit/bin/rabbit", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/youness/gh-events-bigquery/.rabbit/lib64/python3.11/site-packages/rabbit.py", line 506, in cli
    get_results(args.input_file,
  File "/home/youness/gh-events-bigquery/.rabbit/lib64/python3.11/site-packages/rabbit.py", line 385, in get_results
    contributor_type_result = MakePrediction(contributor, apikey, min_events, min_confidence, max_queries, verbose)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/youness/gh-events-bigquery/.rabbit/lib64/python3.11/site-packages/rabbit.py", line 322, in MakePrediction
    imf.extract_features(activities)
  File "/home/youness/gh-events-bigquery/.rabbit/lib64/python3.11/site-packages/important_features.py", line 247, in extract_features
    df_feat = pd.json_normalize(__stats(df), sep='_')
                                ^^^^^^^^^^^
  File "/home/youness/gh-events-bigquery/.rabbit/lib64/python3.11/site-packages/important_features.py", line 176, in __stats
    assert len(unq_contribs)==1, f'Provide activity details for one contributor at a time. The provided contributors are {unq_contribs}'
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: Provide activity details for one contributor at a time. The provided contributors are ['michealroberts' 'cometsinthesky' 'notarun' 'starter-dev']

**To Reproduce**
Attached is the input file used:
[logins.txt](https://github.com/user-attachments/files/16348470/logins.txt)

**Comment by tommens** [comment]
Thank you for this issue report, it looks like we overlooked something. @natarajan-chidambaram can you have a look at it? Perhaps this is related to organisation accounts in GitHub?

**Comment by AlexandreDecan** [comment]
@tommens You're likely to be right. When I query the Events API with an organization account, I get events for the users belonging to this organization (hence explaining why the number of unique contributors is not exactly 1, hence the assertion error). You can check this here: https://api.github.com/users/conda-forge (I see more than one single actor).
I propose to ignore organizations in RABBIT (the input is an account, while an organization is implicitly a "list of accounts", so it makes sense to ignore organizations, but if we do so, we should raise a warning if such an "account" is provided)

@uhourri could you confirm the bug occurs with the given `logins.txt` file and produce the **exact** same error? I don't see ` ['michealroberts' 'cometsinthesky' 'notarun' 'starter-dev']` in the given file.  If this is the file you use, then one of the account is an organization that have, at least, these four accounts.

@natarajan-chidambaram Please also check this line: https://github.com/natarajan-chidambaram/RABBIT/blob/main/rabbit.py#L382 I'm not sure the issue comes from there (and I doubt) but in any case, this line is "unsafe" in the sense we use a `read_csv().to_list()` which can lead to unexpected results. I suggest replacing it with a more "classical" `open` and `readlines()`.

**Comment by uhourri** [comment]
@AlexandreDecan indeed, I checked a bit further, and the bug is produced when the account "observerly" is processed. I checked through the GitHub API and this account is indeed of type "Organization", so that seems to be the reason of the bug. I also checked that the four accounts ['michealroberts' 'cometsinthesky' 'notarun' 'starter-dev'] triggered some events through this organisation, which seems to explain the AssertionError.

**Comment by natarajan-chidambaram** [comment]
@uhourri Thank you spotting and reporting this issue.
@tommens and @AlexandreDecan, yes it is due to the presence of organisation account. In such accounts multiple contributors are involved.
A fix is provided [here](https://github.com/natarajan-chidambaram/RABBIT/tree/dev2.0.1), which is in a branch of this repository. Kindly use this version if the list of login names provided to RABBIT contains organisation accounts.

**Comment by AlexandreDecan** [comment]
I'll check the patch when I'll be back from holidays but thanks for your quick reaction. My suggestion is to skip organisations and display a warning.

**Comment by AlexandreDecan** [comment]
I definitely agree. This is what I meant when I said to ignore these organization accounts and display a warning. Perhaps we shouldn't display a warning but we should mark them as "organization" explicitly, in the same way that we report on apps as well. That way there won't be any ambiguity for the users.

And I'm definitely not against consuming one API hit for that :-)
